# -*- coding: utf-8 -*-
"""Adaboost

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15QQ_-n1LxD_XiXEMdEgHjNvBfZEUNSQ4
"""

import numpy as np
import pandas as pd
import copy
import matplotlib.pyplot as plt

attributes = {
    'age':[0,1],
    'job':["admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
                                       "blue-collar","self-employed","retired","technician","services"],
    'marital':["married","divorced","single"],
    'education':["unknown","secondary","primary","tertiary"],
    'default':["yes","no"],
    'balance':[0,1],
    'housing':["yes","no"],
    'loan':["yes","no"],
    'contact':["unknown","telephone","cellular"],
    'day':[0,1],
    'month':["jan", "feb", "mar","apr","may","jun","jul","aug","sep","oct", "nov", "dec"],
    'campaign':[0,1],
    'pdays':[0,1],
    'previous':[0,1],
    'poutcome':["unknown","other","failure","success"],
    'duration':[0,1]
}

class TreeNode:
    def __init__(self, feature, depth, isleaf, label):
        self.feature = feature
        self.children = {}
        self.depth = depth
        self.isleaf = isleaf
        self.label = label

class ID3:
    def __init__(self, maxdepth,infogain):
        self.root = None
        self.maxdepth = maxdepth
        self.infogainmethod = infogain

    @staticmethod
    def entropy(labels):  
        label, counts = np.unique(labels, return_counts=True)
        probabilities = counts / len(labels)
        logs = np.log2(probabilities)
        entropyattr = 0
        for i in range(len(probabilities)):
            entropyattr -= probabilities[i] * logs[i]
        return entropyattr

    @staticmethod
    def gini(labels):
        label, counts = np.unique(labels, return_counts=True)
        probabilities = counts / len(labels)
        probabilitysquare = [probability*probability for probability in probabilities]
        return 1 - sum(probabilitysquare)

    @staticmethod
    def weighted_gini(labels,weights):
        probability = {}
        uniquelabels = np.unique(labels)
        for i in uniquelabels:
            probability[i] = 0
        for label, weight in zip(labels, weights):
            probability[label] += weight
        probabilitysquare = [probability[label]*probability[label] for label in probability]
        return 1 - sum(probabilitysquare)

    @staticmethod
    def majorityerror(labels):
        label,counts = np.unique(labels, return_counts=True)
        if len(label) == 1:
            return 0
        probabilities = counts / len(labels)
        return min(probabilities)

    def totalEntropy(self, data, attribute):
        totalentropy = 0
        func = None
        for value in attributes[attribute]:
            value_label = data[data[attribute] == value]['y']
            totalentropy += (len(value_label) / len(data)) * (ID3.entropy(value_label))
        return totalentropy

    @staticmethod
    def weightedentropy(data,labels,weights):
        probability = {}
        uniquelabels = np.unique(labels)
        s = sum(weights)
        for i in uniquelabels:
            probability[i] = 0
        for label,weight in zip(labels,weights):
            probability[label] += weight
        for i in uniquelabels:
            probability[i] = probability[i]/s
        attribute_entropy = 0
        for i in np.unique(labels):
            attribute_entropy -= probability[i] * np.log(probability[i])
        return attribute_entropy

    def weightedinformationgain(self,data,attribute,weights):
        information_gain = 0
        for value in attributes[attribute]:
            indexes = data.index[data[attribute] == value]
            attr_weights = [weights[i] for i in indexes]
            
            value_label = data[data[attribute] == value]['y']
            information_gain += (sum(attr_weights)/sum(weights)) * ID3.weightedentropy(data,value_label,attr_weights)
            
        return information_gain

    def informationgain(self,data,attribute):
        infogain = 0
        for value in attributes[attribute]:
            value_label = data[data[attribute] == value]['y']
            if self.infogainmethod == 0:
                infogain += (len(value_label) / len(data)) * (ID3.entropy(value_label))
            elif self.infogainmethod == 1:
                infogain += (len(value_label) / len(data)) * (ID3.gini(value_label))
            else:
                if len(value_label) == 0:
                    return 0
                infogain += (len(value_label) / len(data)) * (ID3.majorityerror(value_label))
        return infogain


    def fit(self,data, attributeList, depth, weights):
        minentropy = 999
        lowest_entropy_attr = None
        labels,counts = np.unique(data['y'],return_counts=True)
        if len(labels) == 1:   
            node = TreeNode(None, depth, True, labels[0])
            return node
        if len(attributeList) == 0:  
            if len(labels) != 0:
                node.label = labels[counts == counts.max()][0]
            return node
        if depth == self.maxdepth: 
            node = TreeNode(None, depth, True, None)
            if len(labels) != 0:
                
                maxsum = 0
                for i in labels:
                    index = data.index[data['y'] == i]
                    weigths_label = [weights[i] for i in index]
                    label_weightage = sum(weigths_label)
                    if maxsum < label_weightage:
                        node.label = i
                        maxsum = label_weightage
            return node
        if len(data) == 0: 
            return TreeNode(None,depth,True,None)
        for a in attributeList: 
            entropy_attr = self.weightedinformationgain(data,a,weights)
            if minentropy > entropy_attr:
                minentropy = entropy_attr
                lowest_entropy_attr = a

        node = TreeNode(lowest_entropy_attr, depth, False, None) 
        if self.root is None:
            self.root = node
        attributeList.remove(lowest_entropy_attr) 
        for value in attributes[lowest_entropy_attr]: 
            new_data = data[data[lowest_entropy_attr] == value]
            attr = copy.deepcopy(attributeList)
            child = self.fit(new_data,attr,depth+1,weights) 
            if child.isleaf is True and child.label is None:
                maxsum = 0
                for i in labels:
                    index = data.index[data['y'] == i]
                    weigths_label = weights[index]
                    label_weightage = sum(weigths_label)
                    if maxsum < label_weightage:
                        child.label = i
                        maxsum = label_weightage
            node.children[value] = child
        return node

    def predict(self,data,node):  
        if node.isleaf:
            return node.label
        feature_value = data[node.feature]
        child = node.children[feature_value]
        return self.predict(data,child)

    @staticmethod
    def calculateErrors(predictedlabels, targetlabels):  
        y_actual = pd.Series(targetlabels,name = 'Actual')
        y_predicted = pd.Series(predictedlabels,name = 'Predicted')
        confusion_matrix = pd.crosstab(y_actual,y_predicted,margins=True)
        labels = np.unique(predictedlabels)
        correctly_predicted = 0
        for label in labels:
            correctly_predicted += confusion_matrix.loc[label,label]
        return 1-correctly_predicted/len(predictedlabels)

    def testdataset(self,testdataset):  
        predictedlabels = []
        for i in range(len(testdataset)):
            predictedlabels.append(self.predict(testdataset.iloc[i], self.root))
        return predictedlabels

class Adaboost:
    def __init__(self,iterations):
        self.modelweights = []
        self.decisionstumps = []
        self.training_iterations = iterations
        self.decisionstumps_errors = []
        self.decisionstumps_testerror = []

    def fit(self, data):
        weights = [1/data.shape[0] for i in range(data.shape[0])]
        attributeList = ['age', 'job', 'marital', 'education', 'default', 'balance', 'housing','loan','contact','day','month',
            'duration','campaign','pdays','previous','poutcome']
        predictedlabels = []
        for i in range(self.training_iterations):
            decisionStump = ID3(1,0)
            decisionStump.fit(data,copy.deepcopy(attributeList),0,weights)
            self.decisionstumps.append(decisionStump)
            for j in range(len(data)):
                predictedlabels.append(decisionStump.predict(data.iloc[j],self.decisionstumps[i].root))
            predictedint = [1 if lable == "yes" else -1 for lable in predictedlabels]
            targetlabels = [1 if lable == "yes" else -1 for lable in data['y']]
            self.decisionstumps_errors.append(self.calculateErrors(predictedint,targetlabels))
            error = sum(weights * (np.not_equal(targetlabels,predictedint)).astype(int))
            self.modelweights.append(1/2 * np.log((1-error)/error))
            weights = [weights[x] * np.exp(-self.modelweights[i]*predictedint[x]*targetlabels[x]) for x in range(len(weights))]
            weights = weights/np.sum(weights)
            predictedlabels = []

    def predict(self,data,root):
        id3obj = ID3(1,0)
        return id3obj.predict(data,root)

    def testdataset(self,testdataset):
        predictedlabels = []
        predictedyn = []
        predictions = []

        for i in range(len(testdataset)):
            for j in range(len(self.decisionstumps)):
                predictions.append(self.predict(testdataset.iloc[i], self.decisionstumps[j].root))
            predicted = [1 if label == "yes" else -1 for label in predictions]
            sum_predicted = np.dot(predicted,self.modelweights)
            predictedlabels.append(np.sign(sum_predicted))
            if sum_predicted>0:
                predictedyn.append("yes")
            else:
                predictedyn.append("no")
            predictions = []
        return predictedyn

    @staticmethod
    def calculateErrors(predictedlabels, targetlabels):
        correctlypredicted = 0
        for predicted,actual in zip(predictedlabels,targetlabels):
            if predicted == actual:
                correctlypredicted += 1
        return 1 - correctlypredicted/len(predictedlabels)

if __name__ == '__main__':
    colnames = ['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day',
                'month','duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']
    dataset = pd.read_csv("train.csv", names=colnames)
    testdataset = pd.read_csv("test.csv", names=colnames)
    for i in dataset.columns[dataset.dtypes == 'int64']:
        dataset[i] = dataset[i].apply(lambda x: 1 if x > dataset[i].median() else 0)

    for i in testdataset.columns[testdataset.dtypes == 'int64']:
        testdataset[i] = testdataset[i].apply(lambda x: 1 if x > testdataset[i].median() else 0)
    print("i             training errors           test errors")
    trainingerror = []
    testerrors = []
    iteration = [x for x in range(1,11)]
    obj = None
    for i in range(1, 11):
        ada = Adaboost(i)
        ada.fit(dataset)
        predictedlabels_train = ada.testdataset(dataset)
        predictedlabels_test = ada.testdataset(testdataset)
        trainingerror.append(Adaboost.calculateErrors(predictedlabels_train, dataset['y']))
        testerrors.append(Adaboost.calculateErrors(predictedlabels_test, testdataset['y']))
        print(i,"              ","%.5f"%trainingerror[i-1],"                   ","%.5f"%testerrors[i-1])
        print("-----------------------------------------------------")
        obj = ada
    predictedlabels_ds = []
    for i in range(obj.training_iterations):
        for j in range(len(testdataset)):
            predictedlabels_ds.append(obj.decisionstumps[i].predict(testdataset.iloc[j], obj.decisionstumps[i].root))
        predictedint = [1 if lable == "yes" else -1 for lable in predictedlabels_ds]
        targetlabels = [1 if lable == "yes" else -1 for lable in testdataset['y']]
        obj.decisionstumps_testerror.append(Adaboost.calculateErrors(predictedint, targetlabels))

print(obj.decisionstumps_testerror)
print(obj.decisionstumps_errors)
print(trainingerror)
print(testerrors)
graph1, axes1 = plt.subplots()
graph2, axes2 = plt.subplots()
axes1.plot(iteration , trainingerror, color='green', label="Train Error")
axes1.plot(iteration , testerrors, color='blue', label="Test Error")
axes1.set_xlabel('Decision stump')
axes1.set_ylabel('Error')
axes1.set_title("Decision Stump vs Train/Test error")
axes1.legend()
print("-------------------------------------------------------------------------")
axes2.plot(iteration ,obj.decisionstumps_errors, color='green', label="Train Error")
axes2.plot(iteration ,obj.decisionstumps_testerror,color= 'blue',label ="Test Error")
axes2.set_xlabel('i')
axes2.set_ylabel('Errors')
axes2.set_title("Error of individual decision stump")
axes2.legend()
plt.show()